import "./css/style.css";

import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Script from "next/script";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${inter.variable} bg-gray-50 font-inter tracking-tight text-gray-900 antialiased`}
      >
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-15803G0RQN"
          strategy="afterInteractive"
        />
        <Script id="gtag-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-15803G0RQN');
          `}
        </Script>
        <div className="flex min-h-screen flex-col overflow-hidden supports-[overflow:clip]:overflow-clip">
          {children}
        </div>
        <Toaster
    position="top-right"
    reverseOrder={false}
    gutter={12}
    toastOptions={{
      duration: 4000,
      style: {
        background: "#111827",
        color: "#fff",
        borderRadius: "12px",
        padding: "16px",
      },
    }}
  />
      </body>
    </html>
  );
}
